### ISSUE TITLE
Fatal error:  RedisDashboard::getType(): Return value must be of type string, null returned

### ISSUE THREAD

**Issue by DimDev** [RobiNN1/phpCacheAdmin#14]
App is started via Docker:

```
  phpcacheadmin:
    image: robinn/phpcacheadmin:1.1.0
    ports:
      - "8083:80"
    environment:
      - PCA_REDIS_0_HOST=redis
      - PCA_REDIS_0_PORT=6379
    links:
      - redis
```

Open http://localhost:8083/?type=redis

**Expected:** Redis UI
**Actual:**

```
Warning: Undefined array key 6 in /var/www/html/src/Dashboards/Redis/TypesTrait.php on line 38

Fatal error: Uncaught TypeError: RobiNN\Pca\Dashboards\Redis\RedisDashboard::getType(): Return value must be of type string, null returned in /var/www/html/src/Dashboards/Redis/TypesTrait.php:38
Stack trace:
#0 /var/www/html/src/Dashboards/Redis/RedisTrait.php(225): RobiNN\Pca\Dashboards\Redis\RedisDashboard->getType(6)
#1 /var/www/html/src/Dashboards/Redis/RedisTrait.php(247): RobiNN\Pca\Dashboards\Redis\RedisDashboard->getAllKeys(Object(Redis))
#2 /var/www/html/src/Dashboards/Redis/RedisDashboard.php(199): RobiNN\Pca\Dashboards\Redis\RedisDashboard->mainDashboard(Object(Redis))
#3 /var/www/html/index.php(71): RobiNN\Pca\Dashboards\Redis\RedisDashboard->dashboard()
#4 {main} thrown in /var/www/html/src/Dashboards/Redis/TypesTrait.php on line 38
```

**Comment by RobiNN1** [comment]
Note: after this fix you get `Unsupported data type: 6` message. Type 6 is stream, which is currently not implemented but I am trying to find a good way to implement it.
