### ISSUE TITLE
phpCacheAdmin not compatible with PHP 7.4 (str_starts_with();)

### ISSUE THREAD

**Issue by p-grucov** [RobiNN1/phpCacheAdmin#4]
Hello,
README says that phpCacheAdmin is compatible with PHP >= 7.4, but it uses str_starts_with() function which is available only on PHP >= 8.0 (https://www.php.net/manual/en/function.str-starts-with.php).

That causes error 500 on Redis page:

![Screenshot 2022-06-30 at 13-43-15 Redis - phpCacheAdmin](https://user-images.githubusercontent.com/101554763/176658552-a10b9038-1230-4787-8753-fd9b0fe120a2.png)

Log from the event:
```
2022/06/30 12:35:56 [error] 1927039#1927039: *33150 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function RobiNN\Pca\Dashboards\Redis\str_starts_with() in /usr/local/share/phpcacheadmin/src/Dashboards/Redis/RedisTrait.php:55
Stack trace:
#0 /usr/local/share/phpcacheadmin/src/Dashboards/Redis/RedisDashboard.php(121): RobiNN\Pca\Dashboards\Redis\RedisDashboard->serverInfo()
#1 /usr/local/share/phpcacheadmin/index.php(36): RobiNN\Pca\Dashboards\Redis\RedisDashboard->ajax()
#2 {main}
  thrown in /usr/local/share/phpcacheadmin/src/Dashboards/Redis/RedisTrait.php on line 55" while reading response header from upstream, client: XX.XX.XX.XX, server: XXX, request: "GET /phpcacheadmin/?type=redis&db=1&ajax&panel=0 HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm-pma.sock:", host: "XXX", referrer: "https://XXX/phpcacheadmin/?type=redis&db=1"
```

**Comment by RobiNN1** [comment]
Ah I thought i added polyfills for php 8.0. I'll fix this asap
